# project
PROJ_NAME: pos-resnet34

EVALUATE: False

DATA:
  CACHE_DIR: data/cache

  CKPT_PATH: ckpt/
  VIZ_PATH: viz/

  SOURCE:
    TRAIN:
      DIR: data/images/union/synth
      LBL_FILE: data/labels/synth/union_train_labels.txt
    VAL:
      DIR: data/images/CMU_Panoptic/hand_labels_synth/all_synth
      LBL_FILE: data/labels/synth/vis_test_labels.txt

  TARGET:
    TRAIN:
      DIR: data/images/union/real
      LBL_FILE: data/labels/real/union_train_labels.txt
    VAL:
      DIR: data/images/CMU_Panoptic/hand_labels/manual_test
      LBL_FILE: data/labels/real/all_test_labels.txt

TRAIN:
  WEIGHT_DECAY: 0.0005
  MAX_ITER: 160000
  BATCH_SIZE: 128
  
  BASE_LR: 0.0001
  START_ITERS: 0

  MCD:
    NUM_K: 1

MODEL:
  RESUME: ""
  PRETRAINED: True
  IMG_SIZE: 64
  NUM_JOINTS: 21
  NUM_LAYERS: 34
  HEATMAP_STRIDE: 2
  NUM_DECONV_LAYERS: 2
  NUM_DECONV_FILTERS:
    - 256
    - 256
  NUM_DECONV_KERNELS:
    - 4
    - 4
  FINAL_CONV_KERNEL: 1

MISC:
  WORKERS: 4
  TEST_INTERVAL: 250
  DISP_INTERVAL: 1
  RANDOM_SEED: 1234
